<?php
require_once ('markup/xhtml-markup.class.php');
require_once("permission-collection.class.php");
  
class User
{
	var $i_id;
	var $s_name;
	var $s_first_name;
	var $s_last_name;
	var $s_email;
	var $i_sign_up_date;
	var $s_location;
	var $s_signature;
	var $i_total_messages;
	var $s_gender;
	var $s_occupation;
	var $s_interests;
	private $s_last_message = '';
	private $s_password;
	private $s_password_confirmation;
	private $b_auto_sign_in;
	private $requested_email;
	private $requested_password;
	private $roles = null;
	private $account_activated = null;
    private $account_disabled = false;
    private $permissions;
    private $salt;

	/**
	 * Creates a new User
	 *
	 * @param int $id
	 * @param string $s_name
	 */
	public function __construct($id = null, $s_name = '')
	{
		if ($id)
			$this->SetId($id);
		if ($s_name)
			$this->SetName($s_name);
        
        $this->permissions = new PermissionCollection();  
	}

	/**
	 * @return void
	 * @param int $i_input
	 * @desc Sets the unique database identifier for the person
	 */
	function SetId($i_input)
	{
		$this->i_id = (int)$i_input;
	}

	/**
	 * @return int
	 * @desc Get the unique id of the person generated by the database
	 */
	function GetId()
	{
		return $this->i_id;
	}

	/**
	 * @return void
	 * @param string $s_input
	 * @desc Sets the given name of the person
	 */
	function SetFirstName($s_input)
	{
		if (is_string($s_input))
			$this->s_first_name = trim($s_input);
	}

	/**
	 * @return string
	 * @desc Gets the given name of the person
	 */
	function GetFirstName()
	{
		return $this->s_first_name;
	}

	/**
	 * @return void
	 * @param string $s_input
	 * @desc Sets the family name of the person
	 */
	function SetLastName($s_input)
	{
		if (is_string($s_input))
			$this->s_last_name = trim($s_input);
	}

	/**
	 * @return unknown
	 * @desc Gets the family name of the person
	 */
	function GetLastName()
	{
		return $this->s_last_name;
	}

	/**
	 * @return void
	 * @param string $s_input
	 * @desc Sets the email address the person is registered with
	 */
	function SetEmail($s_input)
	{
		$this->s_email = trim((string)$s_input);
	}

	/**
	 * @return string
	 * @desc Gets the email address the person is registered with
	 */
	function GetEmail()
	{
		return $this->s_email;
	}

	/**
	 * @return void
	 * @param string $s_input
	 * @desc Sets the screen name the person is known as
	 */
	function SetName($s_input)
	{
		$this->s_name = (string)$s_input;
	}

	/**
	 * @return string
	 * @desc Gets the screen name the person is known as
	 */
	public function GetName()
	{
		return ($this->s_name) ? $this->s_name : $this->GetRealName();
	}

	/**
	 * @return string
	 * @desc Gets the screen name the user is known as, or "you" for the current user
	 */
	public function GetRelativeName()
	{
		if ($this->GetId() and $this->GetId() == AuthenticationManager::GetUser()->GetId())
			return "you";
		else
			return $this->GetName();
	}

	function GetRealName()
	{
		# concatenate and remove extra spaces
		$s_full_name = $this->GetFirstName() . ' ' . $this->GetLastName();
		$s_full_name = str_replace('  ', ' ', $s_full_name);
		$s_full_name = trim($s_full_name);

		return $s_full_name;
	}

	function GetFriendlyName()
	{
		if ($this->s_name and ($this->s_name != $this->GetRealName()))
		{
			return $this->s_name;
		}
		else
			return $this->GetFirstName();
	}

	/**
	 * @return string
	 * @desc Gets a version of the name used to control a sort order
	 */
	function GetSortName()
	{
		$s_name = $this->GetName();
		$s_name = preg_replace("/[()\/,'-]/i", '', $s_name);
		$s_name = preg_replace("/^(The|A) /i", '', $s_name);
		$s_name = str_replace('  ', ' ', $s_name);

		return $s_name;
	}

	/**
	 * Gets the URL for the user's profile page
	 */
	public function GetUserProfileUrl()
	{
		# Absolute URL because used as property of user in RDFa
		return "https://" . $_SERVER['HTTP_HOST'] . "/you/profile.php?id=" . $this->GetId();
	}

	/**
	 * Gets the URL to edit the user
	 */
	public function GetEditUserUrl()
	{
		return "/yesnosorry/personedit.php?item=" . $this->GetId();
	}

	/**
	 * @return void
	 * @param string $s_input
	 * @desc Sets the email address the person would like to have as a username
	 */
	public function SetRequestedEmail($s_input)
	{
		$this->requested_email = trim((string)$s_input);
	}

	/**
	 * @return string
	 * @desc Gets the email address the person would like to have as a username
	 */
	public function GetRequestedEmail()
	{
		return $this->requested_email;
	}

	/**
	 * @return void
	 * @param string $s_input
	 * @desc Sets the unencrypted password used to sign in
	 */
	public function SetPassword($s_input)
	{
		$this->s_password = (string)$s_input;
	}

	/**
	 * @return string
	 * @desc Gets the unencrypted password used to sign in
	 */
	public function GetPassword()
	{
		return $this->s_password;
	}

	/**
	 * @return void
	 * @param string $s_input
	 * @desc Sets the new unencrypted password used to sign in
	 */
	public function SetRequestedPassword($s_input)
	{
		$this->requested_password = (string)$s_input;
	}

	/**
	 * @return string
	 * @desc Gets the new unencrypted password used to sign in
	 */
	public function GetRequestedPassword()
	{
		return $this->requested_password;
	}

	/**
	 * @return void
	 * @param string $s_input
	 * @desc Sets the confirmation copy of the unencrypted password used to sign in
	 */
	function SetPasswordConfirmation($s_input)
	{
		$this->s_password_confirmation = (string)$s_input;
	}

	/**
	 * @return string
	 * @desc Gets the confirmation copy of the unencrypted password used to sign in
	 */
	function GetPasswordConfirmation()
	{
		return $this->s_password_confirmation;
	}

	function SetSignUpdate($i_input)
	{
		if (is_numeric($i_input))
		{
			$this->i_sign_up_date = (int)$i_input;
		}
	}

	function GetSignUpDate()
	{
		return $this->i_sign_up_date;
	}

	function SetGender($s_input)
	{
		if (is_string($s_input))
			$this->s_gender = $s_input;
	}

	function GetGender()
	{
		return $this->s_gender;
	}

	function SetLocation($s_input)
	{
		if (is_string($s_input))
			$this->s_location = $s_input;
	}

	function GetLocation()
	{
		return $this->s_location;
	}

	function SetOccupation($s_input)
	{
		$this->s_occupation = (string)$s_input;
	}

	function GetOccupation()
	{
		return $this->s_occupation;
	}

	function SetInterests($s_input)
	{
		if (is_string($s_input))
			$this->s_interests = $s_input;
	}

	function GetInterests()
	{
		return $this->s_interests;
	}

	function SetSignature($s_input)
	{
		$this->s_signature = (string)$s_input;
	}

	function GetSignature()
	{
		return $this->s_signature;
	}

	/**
	 * @return void
	 * @param bool $b_input
	 * @desc Sets whether to store a cookie which automatically signs the person in
	 */
	function SetAutoSignIn($b_input)
	{
		$this->b_auto_sign_in = (bool)$b_input;
	}

	/**
	 * @return bool
	 * @desc Gets whether to store a cookie which automatically signs the person in
	 */
	function GetAutoSignIn()
	{
		return $this->b_auto_sign_in;
	}

	function SetTotalMessages($i_input)
	{
		if (is_numeric($i_input))
			$this->i_total_messages = (int)$i_input;
	}

	function GetTotalMessages()
	{
		return $this->i_total_messages;
	}

	function SetLastMessage($s_input)
	{
		$this->s_last_message = md5($s_input);
	}

	function GetLastMessage()
	{
		return $this->s_last_message;
	}

	function MatchLastMessage($s_input)
	{
		return (md5($s_input) == $this->s_last_message);
	}

	/**
	 * @return bool
	 * @desc Gets whether the person is currently signed in to the site
	 */
	function IsSignedIn()
	{
		return $this->Permissions()->HasPermission(PermissionType::EditPersonalInfo());
	}

	/**
	 * Gets the URI which uniquely identifies this user
	 */
	public function GetLinkedDataUri()
	{
		return "https://www.stoolball.org.uk/id/user/" . $this->GetId();
	}

	/**
	 * Gets the security roles assigned to the user
	 * @return Collection
	 */
	public function Roles()
	{
		if (is_null($this->roles))
		{
			require_once ("collection.class.php");
			$this->roles = new Collection( array(), "Role");
		}
		return $this->roles;
	}

    /**
     * Sets whether this account has been activated
     * @param $activated bool
     */
    public function SetAccountActivated($activated)
    {
        $this->account_activated = (bool)$activated;
    }

    /**
     * Gets whether this account has been activated
     * @return bool
     */
    public function GetAccountActivated()
    {
        return $this->account_activated;
    }

	/**
	 * Sets whether this account has been disabled
	 * @param $disabled bool
	 */
	public function SetAccountDisabled($disabled)
	{
		$this->account_disabled = (bool)$disabled;
	}

	/**
	 * Gets whether this account has been disabled
	 * @return bool
	 */
	public function GetAccountDisabled()
	{
		return $this->account_disabled;
	}

    /**
     * Gets the security permissions granted to the user
     * @return PermissionCollection
     */
    public function Permissions() 
    {
        return $this->permissions;
    }

    /**
     * Sets the password salt for this account
     * @param $salt string
     */
    public function SetPasswordSalt($salt)
    {
        $this->salt = (string)$salt;
    }

    /**
     * Gets the password salt for this account
     * @return string
     */
    public function GetPasswordSalt()
    {
        return $this->salt;
    }
}
?>